name: Pull request main

on:
  pull_request_target:
    branches: [main]
    paths-ignore: ["docs/**"]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  test:
    needs: pre-commit
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      build_target: dev
    secrets: inherit
